version: '3.8'

services:
  auth-redis:
    image: redis:latest
    container_name: auth-redis
    ports:
      - "6379:6379"
  
  auth-service:
    build:
      context: ./Auth
    container_name: auth-service
    ports:
      - "3001:3001"
    depends_on:
      - auth-redis
    environment:             
      - DATABASE_URL=postgresql://neondb_owner:npg_WJiuZLjM95Uc@ep-winter-glitter-a1xql2bp-pooler.ap-southeast-1.aws.neon.tech/auth_e3265989-214d-4ae2-8399-45af40bbe4af?sslmode=require
      - REDIS_URL=redis://auth-redis:6379
      - SERVICE_NAME=Auth
      - JWT_TOKEN_PRIVATE_KEY=|-----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCsYSpOpCWI/BtF
        IhQpS193YsTEwL60nvLvLcwHyXD6AWacFiUAAoTYTek9hAEbO+TcDJzp2lXLstXM
        ldcA2QLW3hKgW+StQi48jIgs/7rqKpbwSkL9tMGNOFAbFq0cOxdWoUTem6/QC7kB
        A5Ct2UO12cgXqdci1VAfBvh7TAm+qGhDxLFxWfHa4pLTVvDHfyUpc1j/y+U5sm9I
        miSTNf+cDmhV484Xa3n3gIswhlJR4jfB2UAokxSKy2RDY14ATsP0EgO/NZS8hPPg
        7cZ6T6KW3xkCcs5D0erxTQtZvQaDR+ltixV5Ds4ShFbjVmC9vod6Y845OYZNgohj
        1wzQ2cxfAgMBAAECggEAAqJgBe3ZMdbFggUdCknGiLWHU4jwaz8n28f3H4+NGW/s
        JftxSJKY3GI1ryuphYIg97Esz3DO/vKZsYLzbj2Eb/WJyLNdHwFVpOvDL4Ms9Ujw
        mQmtsz8q6MjIoQc98vMTLM8ONw+fYxawqu0/EtJSlZMeEJTT0U3g59X0A4cxQ8Xr
        fRGZN8usgnje8ekT3a6d6IHTRr4CZZXZ7wXtDX7NLDaSnmDKmN7ZzQBm5mRjiN0Y
        d/3z1PCXbwLCkjJEq8HkRFVCuF3dRu3jgvWSLg0OIqnz9XEz0cH1k9bgXDZptS7l
        GJk39WGwDPWjUabtejVHydO8Ei6dAttmctANh2rnqQKBgQDaZ8oD1ALOqhWy55vP
        8o25u7sUNP/YGBmjnKzWK/uAtY8GBcRd8NigKppIVOMfJiF1ciNrbzcMSqgvn3vp
        TOOfnSsSOyBatxiD7f+rvbcBjV3zUH6oyyNNKY5Q0jAt1L9m/lIYgSc0eripwCTT
        rPqr7V8O+gRCr+EmwXzcBDmtKwKBgQDKDTV9RVgU9dGOsVobgxCZ5BhMgPXeVk9l
        peivlrcMkl9y6c0LOxilSkV3pZ3WXEB+EWwSby2hiw/69tthx3fIHU8SFk3EYsJw
        MImx5hRWQW783xaSydkEBZge8q6KPtpCm5CBqjIPcETmE+o+P8dKACo2lYzjj6Q/
        4S9V8b1LnQKBgQCSZiP58PF4ynYFGE9PUs1BhN9gKi6dEXqOO4V3gr/xhMI8TT1V
        ow3yPtxwQ8aCqLKg4UNwznnd2WVnlsYempWx9k5ayBtl83mRZcWNv3uepL4nTPu5
        9YDSRlrJPjthXUx3o14wYtJ+0QxbbRrCcR8Og+zGQzz73p1TtzsU2Bg5RQKBgQCw
        tyLMQKUMF/9DZPwhSd1wKx3Rc40W+7gPeC7tu8y3UyHmGHR8WSByGGZvgcttW1wQ
        pt41tUVcn4rHfbZca5/oxzGL6TP1Ckdy5hDYJhotYqdWxSsyERYcPWRR1QEw6k3s
        qbCWp6uG8zNfY5WhAhkkMMa63MvPj6chM6s56OcdxQKBgFN+Sf+BsZUXCYq5rgvg
        1AEJdLm0ZGRoz98u5w98NOALMM3Tv5s+Nin9N+WhSlHXjEYQ8WBPAGrXo84unhOw
        6GprsLxySl6wIXG7o/ovsILLgI8ujssMg3CMu6KwZA2aR5QRuGcHWjc/8RWCeYgz
        o4FL74eIq++rldWKImhNrx4P
        -----END PRIVATE KEY-----
      - JWT_TOKEN_PUBLIC_KEY=| -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArGEqTqQliPwbRSIUKUtf
          d2LExMC+tJ7y7y3MB8lw+gFmnBYlAAKE2E3pPYQBGzvk3Ayc6dpVy7LVzJXXANkC
          1t4SoFvkrUIuPIyILP+66iqW8EpC/bTBjThQGxatHDsXVqFE3puv0Au5AQOQrdlD
          tdnIF6nXItVQHwb4e0wJvqhoQ8SxcVnx2uKS01bwx38lKXNY/8vlObJvSJokkzX/
          nA5oVePOF2t594CLMIZSUeI3wdlAKJMUistkQ2NeAE7D9BIDvzWUvITz4O3Gek+i
          lt8ZAnLOQ9Hq8U0LWb0Gg0fpbYsVeQ7OEoRW41Zgvb6HemPOOTmGTYKIY9cM0NnM
          XwIDAQAB
          -----END PUBLIC KEY-----
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - NODE_ENV=development
      - EMAIL_USER=ashishchoudhari224@gmail.com
      - EMAIL_PASS=qnps jhmd rgpa qjyx
      - FRONTEND_BASE_URL=http://localhost:3000
      - PORT=3001

  # user-redis:
  #   image: redis:latest
  #   container_name: user-redis
  #   ports:
  #     - "6380:6379"

  # user-management-service:
  #   build:
  #     context: ./UserManagement
  #   container_name: user-management-service
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - user-redis
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3002
  #     - SERVICE_NAME=User Management
  #     - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
  #     - DATABASE_URL="postgresql://neondb_owner:npg_Ap0fR2EhSwYb@ep-sweet-fog-a15wy3ig-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

  #     - JWT_TOKEN_PUBLIC_KEY=|-----BEGIN PUBLIC KEY-----
  #       MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArGEqTqQliPwbRSIUKUtf
  #       d2LExMC+tJ7y7y3MB8lw+gFmnBYlAAKE2E3pPYQBGzvk3Ayc6dpVy7LVzJXXANkC
  #       1t4SoFvkrUIuPIyILP+66iqW8EpC/bTBjThQGxatHDsXVqFE3puv0Au5AQOQrdlD
  #       tdnIF6nXItVQHwb4e0wJvqhoQ8SxcVnx2uKS01bwx38lKXNY/8vlObJvSJokkzX/
  #       nA5oVePOF2t594CLMIZSUeI3wdlAKJMUistkQ2NeAE7D9BIDvzWUvITz4O3Gek+i
  #       lt8ZAnLOQ9Hq8U0LWb0Gg0fpbYsVeQ7OEoRW41Zgvb6HemPOOTmGTYKIY9cM0NnM
  #       XwIDAQAB
  #       -----END PUBLIC KEY-----
  #     - CLIENT_ID=7d2a6d05-aaae-439a-87e0-8eb6ac2a6c0e
  #     - CLIENT_SECRET=XiGfySozvMZJAPXoJgSPHDl7TCW2oY74n7fiunMQ0W0=
  #     - AUTH_SERVICE_URL=http://localhost:3001
  #     - REDIS_URL=redis://user-redis:6379
